Repository atom-community/atom-ide-outline, pull requests merged in 2020-07, with the labels that each got.

#12 refactor: move styles under main class
  styles/atom-ide-outline.less
Labels: refactor

#18 remove excess less
  styles/atom-ide-outline.less
Labels: refactor

#34 Atomic packages
  .eslintrc.json
  babel.config.js
  package-lock.json
  package.json
  rollup.config.js
  rollup.config.mjs
Labels: dependencies, enhancement

#35 Support kind and plainText
  src/outlineView.js
Labels: bug, enhancement

#41 Folding
  CHANGELOG.md
  preview.png
  src/outlineView.ts
  styles/atom-ide-outline.less
Labels: enhancement

#42 Fix icons not showing
  src/outlineView.ts
Labels: bug

#44 Using Pnpm
  .github/workflows/CI.yml
  .github/workflows/bump_deps.yml
  .gitignore
  package-lock.json
  package.json
  pnpm-lock.yaml
  script/install-package-deps.js
Labels: dependencies, enhancement

#47 fix: clean up if the editor is closed
  .prettierignore
  CHANGELOG.md
  src/main.ts
  src/outlineView.ts
Labels: bug

#48 Beautiful fold buttons
  styles/atom-ide-outline.less
Labels: enhancement

#49 Scrolling and highlighting based on the cursor position
  CHANGELOG.md
  preview.png
  src/main.ts
  src/outlineView.ts
  styles/atom-ide-outline.less
Labels: enhancement

#52 sort entries based on the line number
  CHANGELOG.md
  src/main.ts
  src/outlineView.ts
Labels: enhancement

#56 fix: disposable leak fix
  src/main.ts
Labels: bug

#60 correct indentation
  .github/workflows/CI.yml
  src/outlineView.ts
Labels: bug, enhancement
