Repository atom-community/atom-ide-outline, pull requests merged in 2021-03, with the labels that each got.

#95 Fix initial outline
  src/main.ts
  src/tsconfig.json
  src/utils.ts
Labels: bug

#93 Styles tweak
  src/outlineView.ts
  styles/atom-ide-outline.less
Labels: bug, enhancement

#96 feat: make outline condensed + move indentation logic to CSS
  preview.png
  src/outlineView.ts
  styles/atom-ide-outline.less
Labels: enhancement, refactor

#100 skip re-rendering if the content of the outline is the same + misc
  .prettierignore
  package.json
  pnpm-lock.yaml
  src/outlineView.ts
Labels: performance

#102 refactor: separate element for outline list and content
  spec/outline-spec.js
  spec/outline-view-spec.js
  spec/runner.js
  src/outlineView.ts
  styles/atom-ide-outline.less
Labels: refactor

#104 fix: outline getting stuck on "no provider"
  src/outlineView.ts
Labels: bug

#103 Fix disappearing toolbar
  src/outlineView.ts
  styles/atom-ide-outline.less
Labels: bug

#98 Toolbar for outline
  src/main.ts
  src/outlineView.ts
  styles/atom-ide-outline.less
Labels: enhancement

#106 fix: reveal button doesn't scroll into the entry
  src/outlineView.ts
Labels: bug
